describe(`Navigate the match-plus page`,()=>{
    const matchSel = require('../../selectors/matchPlus.sel')
    before(()=>{
        cy.visit(Cypress.env("uiUrl"))
    })
    it(`Check the events of match-plus page`,()=>{

        cy.get(matchSel.chooseMatch).check({force: true})
        cy.get('#2293180').click({force: true})
        cy.get(':nth-child(1) > .btn').should("have.contain","Match+").click()
        cy.get(`:nth-child(1) ${matchSel.eventTitle}`).should("have.contain","Goals")
        cy.get('#goal')
        cy.get(`:nth-child(2) ${matchSel.eventTitle}`).should("have.contain","Penalties")
        cy.get('#penalty')
        cy.get(`:nth-child(3) ${matchSel.eventTitle}`).should("have.contain","Shots")
        cy.get('#target')
        cy.get(`:nth-child(4) ${matchSel.eventTitle}`).should("have.contain","Shots On Target")
        cy.get('#shottarget')
        cy.get(`:nth-child(5) ${matchSel.eventTitle}`).should("have.contain","Skill")
        cy.get('#skill')
        cy.get(`:nth-child(6) ${matchSel.eventTitle}`).should("have.contain","Saves/Blocks")
        cy.get('#save')
        cy.get(`:nth-child(7) ${matchSel.eventTitle}`).should("have.contain","Near Misses")
        // cy.get('#big chance')
        cy.get(`:nth-child(8) ${matchSel.eventTitle}`).should("have.contain","Close Range Shots")
        cy.get('#close')
        cy.get(`:nth-child(9) ${matchSel.eventTitle}`).should("have.contain","Mid Range Shots")
        cy.get('#mid')
        cy.get(`:nth-child(10) ${matchSel.eventTitle}`).should("have.contain","Long Range Shots")
        cy.get('#longrange')
        cy.get(`:nth-child(11) ${matchSel.eventTitle}`).should("have.contain","Direct Freekicks")
        cy.get('#directkick')
        cy.get(`:nth-child(12) ${matchSel.eventTitle}`).should("have.contain","Corners")
        cy.get('#corner')
        cy.get(`:nth-child(13) ${matchSel.eventTitle}`).should("have.contain","Crosses")
        cy.get('#crosses')
        cy.get(`:nth-child(14) ${matchSel.eventTitle}`).should("have.contain","Offside")
        cy.get('#offside')
        cy.get(`:nth-child(15) ${matchSel.eventTitle}`).should("have.contain","Tackles")
        cy.get('#tackle')
        cy.get(`:nth-child(16) ${matchSel.eventTitle}`).should("have.contain","Throw-ins")
        cy.get('#throwin')
        cy.get(`:nth-child(17) ${matchSel.eventTitle}`).should("have.contain","Fouls")
        cy.get('#foul')
        cy.get(`:nth-child(18) ${matchSel.eventTitle}`).should("have.contain","Cards")
        cy.get('#card')
        cy.get(`:nth-child(19) ${matchSel.eventTitle}`).should("have.contain","Chances Created")
        cy.get('#assisted')
        cy.get(`:nth-child(20) ${matchSel.eventTitle}`).should("have.contain","VAR")
        cy.get('#var')  
        cy.get(`:nth-child(21) ${matchSel.eventTitle}`).should("have.contain","Passes")
        cy.get('#passes')
        cy.get(`:nth-child(22) ${matchSel.eventTitle}`).should("have.contain","Substitutions")
        cy.get('#substitution')
    })
})